sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: 
    username: 
    password: 
  alioss:
    access-key-id: 
    access-key-secret: 
    endpoint: oss-ap-southeast-3.aliyuncs.com
    bucket-name: sky-itcast-my-24
  redis:
    password: 123456
    port: 6379
    host: localhost
    database: 10
  wechat:
    appid: 
    secret: 
    mchid : 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key-pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07C98952A96EC980368ACFC.pem
    notifyUrl: https://505df0ea.r2.cpolar.cn/notify/paySuccess
    refundNotifyUrl: https://505df0ea.r2.cpolar.cn/notify/refundSuccess
