sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    access-key-id: LTAI5t7NCxa1gJSa6mydf14V
    access-key-secret: UnENbruKHvwN3jKyD8w6mZh8V9rGTM
    endpoint: oss-ap-southeast-3.aliyuncs.com
    bucket-name: sky-itcast-my-24
  redis:
    password: 123456
    port: 6379
    host: localhost
    database: 10
